-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 12:28:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reporte` (
  `Reporte_ID` INT NOT NULL,
  `Reporte_detalle` VARCHAR(45) NOT NULL,
  `Rerporte_Fecha` VARCHAR(45) NOT NULL,
  `Usuario_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Reporte_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Usuario_ID` INT NOT NULL,
  `usuario_nombre` VARCHAR(45) NOT NULL,
  `usuario_contraseña` VARCHAR(45) NOT NULL,
  `usuario_rol` VARCHAR(45) NOT NULL,
  `Usuario_fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Usuario_ID`),
  INDEX `usuario:Id` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `Usuario_ID`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Reporte` (`Reporte_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Regiistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Regiistro` (
  `Registro_ID` INT NOT NULL,
  `Registro_fecha` VARCHAR(45) NOT NULL,
  `Registro_codigo` INT NOT NULL,
  `Usuario_ID` INT NULL,
  `Visitante_ID` INT NULL,
  PRIMARY KEY (`Registro_ID`),
  CONSTRAINT `Usuario_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Usuario` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `inventario_ID` INT NOT NULL,
  `inventario_estado` VARCHAR(45) NOT NULL,
  `inventario_observaciones` VARCHAR(45) NOT NULL,
  `Registro_ID` INT NULL,
  `Dispositivo_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`inventario_ID`),
  INDEX `Registri_ID_idx` (`Registro_ID` ASC) VISIBLE,
  CONSTRAINT `Registri_ID`
    FOREIGN KEY (`Registro_ID`)
    REFERENCES `mydb`.`Regiistro` (`Registro_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visitante` (
  `Visitante_ID` INT NOT NULL,
  `Visitante_nombre` VARCHAR(45) NOT NULL,
  `Visitante_apellido` VARCHAR(45) NOT NULL,
  `Visitante_cedula` VARCHAR(45) NOT NULL,
  `Visitante_ficha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Visitante_ID`),
  CONSTRAINT `Visitante_ID`
    FOREIGN KEY (`Visitante_ID`)
    REFERENCES `mydb`.`Regiistro` (`Registro_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dispositivo` (
  `Dispositivo_ID` INT NOT NULL,
  `Dispositivo_marca` VARCHAR(45) NOT NULL,
  `Dispositivo_serie` VARCHAR(45) NOT NULL,
  `Dispositivo_tipo` VARCHAR(45) NOT NULL,
  `Dispositivo_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dispositivo_ID`),
  CONSTRAINT `Dispositivo_ID`
    FOREIGN KEY (`Dispositivo_ID`)
    REFERENCES `mydb`.`Inventario` (`inventario_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
